---
# defaults file for kvm_provision
base_image_name: Fedora-Cloud-Base-36-1.5.x86_64.qcow2
base_image_url: https://download.fedoraproject.org/pub/fedora/linux/releases/36/Cloud/x86_64/images/{{ base_image_name }}
# base_image_sha: b9b621b26725ba95442d9a56cbaa054784e0779a9522ec6eafff07c6e6f717ea
libvirt_pool_dir: "/var/lib/libvirt/images"
vm_name: f36-dev
vm_vcpus: 1
vm_ram_mb: 1024
vm_net: default
vm_root_pass: test123
cleanup_tmp: no
ssh_key: /root/.ssh/id_rsa.pub